### ISSUE TITLE
Improve new-user documentation and document config file.

### ISSUE THREAD

**Issue by vext01** [chipsenkbeil/distant#144]
Hi,

I found distant this morning (in the hope of using distant.nvim).

After installing, I tried to run a manager and got:

```
$ ~/.cargo/bin/distant manager listen                                                     
Failed to start manager

Caused by:
    0: Failed to start manager at socket "/run/distant.sock"
    1: No such file or directory (os error 2)
```

This is because my user doesn't have access to `/run`.

This raises some questions:

# Am I supposed to run this as root?

(I hope not)

# Where is the config file?

Using `strace`, I found that on Linux it's at `~/.config/distant/config.toml`, but it would be good to document this somewhere.

# What is the format of the config file?

Grepping the sources, I thought I could do something like:

```
[manager.network]
unix_socket = "~/.distant.sock"
```

But this isn't right.

I'd really like to try out distant, but I've fallen at the first hurdle. A bit more user documentation would be much appreciated, even if it's just a short addition to the `Example` section in the `README.md`.

Thanks

**Comment by chipsenkbeil** [comment]
@vext01 hey there, thanks for the feedback! Documentation is scarce as the tool kept changing over the last N iterations; however, once 0.20 is released, I'm planning to flesh out a dedicated website for documentation related to using distant.

> Am I supposed to run this as root?
> (I hope not)

No, you do not need to run the manager, server, or client as root. However, if you are trying to start the manager as a service, some service managers on Linux do not support user-level tasks (e.g. runit does not, but systemd does). You can always start the manager yourself and connect to it through a user-owned unix socket (or windows pipe).

Have you tried `distant manager listen --user` to start the manager? By default, it tries to use a global socket path. 
Providing the user flag should indicate to leverage a [user-specific path](https://github.com/chipsenkbeil/distant/blob/0633530a132929db94aa318f4781280e7903b067/src/paths.rs#L48) of `/run/user/1001/distant/{user}.distant.sock`. If the `/run` directory isn't accessible at all, then you'd need to specific a different socket path, which you can do with the cli via `distant manager listen --unix-socket ~/my.sock`.

> What is the format of the config file?

The config file is relatively new and absolutely needs documentation. I need to verify that toml is parsed as expected as well, since this is using a generated toml parser.

**Comment by chipsenkbeil** [comment]
Oh, and for distant.nvim, are you using the `PrepareForDistant16` branch? Or the main branch? It's been in the works for awhile to update the neovim plugin to use the newer distant that provides a [JSON Lines API](https://jsonlines.org/) over the old Lua shared library. Despite the name, the above branch supports distant 0.19 today. You should not need to start a manger yourself to use that branch, as the plugin will start it for you.

**Comment by vext01** [comment]
Hi,

Thanks for the response!

Glad to hear you plan to expand the docs.

> Have you tried distant manager listen --user

I was unaware of this. I was just following the instructions in the README.md

> are you using the PrepareForDistant16 branch

I haven't got as far as trying the vim plugin yet. Still working out `distant` :)

I'll try again tomorrow and let you know how i get on.

Another thing that crossed my mind: In the "Interacting with a remote machine" section of the readme you are showing what you can do with distant. To the uninitiated it kind of sounds like you reimplemented a remote shell, however I think this is different somehow. It may be worth clarifying?

I also was wondering if vim plugins that use the file-system have to be "distant-aware". For example, will `telescope` (fuzzy finding file/buffer opener) "just work" with distant, or would it need to be modified?

Cheers

**Comment by vext01** [comment]
Hi chip,

I've just had a play around again.

Local machine is OpenBSD, remote machine in Debian. `distant` installed by `cargo` on both sides.

One thing to clarify in `README.md`, the manager runs on the client side, not the server side (right?).

Manager starts now:
```
$ distant manager listen --user               
[flexi_logger][ERRCODE::Time] flexi_logger works with UTC rather than with local time, caused by IndeterminateOffset
    See https://docs.rs/flexi_logger/latest/flexi_logger/error_info/index.html#time
```

Not sure if that warning is important.

When using a client, I notice that the ssh config isn't read, so distant wasn't using my jump host. Had to make an ssh tunnel manually (feature request?).

After doing the tunneling:
```
$ distant client launch ssh://user@localhost:2222 --distant /home/user/.cargo/bin/distant

[flexi_logger][ERRCODE::Time] flexi_logger works with UTC rather than with local time, caused by IndeterminateOffset
    See https://docs.rs/flexi_logger/latest/flexi_logger/error_info/index.html#time
Using ssh2 to connect to user@localhost:2222
SSH-2.0-OpenSSH_8.4p1 Debian-5+deb11u1
Failed to connect to server

Caused by:
    Connection refused (os error 61)
```

I've verified that `ssh user@localhost -p2222` works. It does.

Running:
```
$ distant server listen --host ssh
```

manually on the remote side seems to work. It prints a url and blocks. I assume that's right.

I tried launching a manager on the remote side too. No joy. What am I missing?

P.S.

```
        --distant <distant>
            Path to distant program on remote machine to execute via ssh; by default, this program
            needs to be available within PATH as specified when compiling ssh (not your login shell)
```

I don't understand the wording of this. When you say "when compiling ssh", are you talking about when you compile the OpenSSH client?

Do you just meant to say, if `--distant` isn't specified, then `$PATH` is searched?

Cheers.

**Comment by chipsenkbeil** [comment]
> One thing to clarify in README.md, the manager runs on the client side, not the server side (right?).

Yep! The manager is meant to run client side as it manages multiple server connections for you such that you can run subsequent actions like `distant client shell` and `distant client action copy {src} {dst}` without needing to reconnect and reauthenticate each time.

> Not sure if that warning is important.

It shouldn't be, but some logging may not show up in the output files.

> When using a client, I notice that the ssh config isn't read, so distant wasn't using my jump host. Had to make an ssh tunnel manually (feature request?).

Distant uses [wezterm-ssh](https://github.com/wez/wezterm/tree/main/wezterm-ssh) for all of the ssh features. It does support reading a config file, but not everything in a config file works. In particular, ssh tunnels are not supported (yet).

> Caused by:
    Connection refused (os error 61)

Has an instance of a distant server started on your remote machine? Launch does two things: ssh into a remote machine to start the distant server and then connect to the distant server over TCP. The connection refused can be a sign that a connection between the remote machine and the distant server failed because either the server was not running or the bound port was not accessible.

The url printed includes the bound port as part of the details. All of that is used by the manager when launching the server to know the key to use for authentication and the port to connect through.

> I don't understand the wording of this. When you say "when compiling ssh", are you talking about when you compile the OpenSSH client?

Been a little while since I wrote that, so my memory may be off. When executing a command without a login shell, the server has a fixed `PATH` it uses to look for binaries if you don't provide an absolute path. The `--distant` argument lets you provide an explicit path in case the binary isn't somewhere the server can find.

To my knowledge, you can set the `PATH` on the server in `~/.ssh/environment`, but this needs to be enabled by `PermitUserEnvironment yes` in `sshd_config`.

**Comment by vext01** [comment]
> The connection refused can be a sign that a connection between the remote machine and the distant server failed because either the server was not running or the bound port was not accessible.

This is likely a network accessibility issue. Due to matters out of my hands I have to connect to the remote host via a jump host that I only have access to port 22 of.

Perhaps this isn't going to work...

**Comment by chipsenkbeil** [comment]
Ah, you can use ssh mode instead to talk through ssh instead of distant. But it doesn't support hopping across hosts yet. So either the server needs to have ssh available directly or you tunnel yourself.

You can also manually tunnel to distant via ssh, which I've done at work.

**Comment by carrascomj** [comment]
I am also confused about the process with distant and distant.nvim, but I am glad that you have already thought about improving the docs.

Maybe my user story helps to point what it is not clear for new users.

My setup is the following:

```
distant.nvim: v0.2 branch)
distant: 0.20.0-alpha.2 (in the path of both remote and local machine)
nvim: 0.8.0
```

```lua
config = function()
    require('distant').setup {
    -- I tried both with and without the chip_default
      ['*'] = require('distant.settings').chip_default(),
     -- I read in the changelog that this is the way to do it
      ssh = { ssh_identity_file = {'/path/to/key.pem' }},
    }
  end

```

I tried to go through ssh:

```
:DistantLaunch ssh://$USERNAME:$IP_REMOTE:$PORT
```

(replacing the variables with actual values). This fails with the error:

```
Failed (1): Failed to connect to server                                                      
Caused by:
No route to host (os error 113) 
```

At this point, I was not sure if I needed to install distant on the remote server (that was not the case for the previous version). I tried installing it with `cargo`. On the **remote** machine:

```
cargo install distant --version 0.20.0-alpha.2
```

But then, after running
```
distant manager service install --user
distant manager service start
```

I got

```
Failed to start service

Caused by:
    Failed to start distant-manager.service: Interactive authentication required.
    See system logs and 'systemctl status distant-manager.service' for details.
```

This is the info on `systemctl status --user  distant-manager.service`:

```
● distant-manager.service - distant-manager
     Loaded: loaded (/home/jorge/.config/systemd/user/distant-manager.service; enabled; vend>
     Active: inactive (dead)
```

Then, I tried listening manually with `distant manager listen`, this is the error:

```
Failed to start manager

Caused by:
    No such file or directory (os error 2)
```

I still don't know how to do this, probably I am doing something dumb.

**Comment by chipsenkbeil** [comment]
> I tried to go through ssh:
> 
> ```
> :DistantLaunch ssh://$USERNAME:$IP_REMOTE:$PORT
> ```
> 
> (replacing the variables with actual values). This fails with the error:
> 
> ```
> Failed (1): Failed to connect to server                                                      
> Caused by:
> No route to host (os error 113) 
> ```
> 
> At this point, I was not sure if I needed to install distant on the remote server (that was not the case for the previous version). 

If with distant.nvim v0.1, you were using ssh mode, then you actually want to use `DistantConnect ssh://...`, which will use ssh and not require a distant server on your remote machine.

> I tried installing it with `cargo`. On the **remote** machine:
> 
> ```
> cargo install distant --version 0.20.0-alpha.2
> ```
> 
> But then, after running
> 
> ```
> distant manager service install --user
> distant manager service start
> ```
> 
> I got
> 
> ```
> Failed to start service
> 
> Caused by:
>     Failed to start distant-manager.service: Interactive authentication required.
>     See system logs and 'systemctl status distant-manager.service' for details.
> ```
> 

It looks like you installed the manager as a user-level service, but you tried to start it as a global service. What happens when you try to run `distant manager service start --user`?


> Then, I tried listening manually with `distant manager listen`, this is the error:
> 
> ```
> Failed to start manager
> 
> Caused by:
>     No such file or directory (os error 2)
> ```

Listen also accepts a `--user` flag. What the manager listen is doing is trying to bind to a unix domain socket. Without the `--user` flag, it does this on Linux at a place that is globally accessible, but which you may not have permission to touch unless you were root or have said permission. With the `--user` flag, it's supposed to create a domain socket somewhere that is accessible by your user.

You can get more error details by running via `distant manager listen --log-level trace --log-file /tmp/manager.log` to see what's going on, but my guess is that you want to include the `--user` flag! :)

> I still don't know how to do this, probably I am doing something dumb.

Absolutely nothing dumb here. This is an example of a couple of things:

1. The binary and neovim plugin are rapidly changing, so what worked for you in the past has broken.
2. The documentation is non-existent (other than `distant.nvim/docs/distant.txt`), which is because things have changed so much. That's on me, and it's on my list to build out properly soon!

So my thanks for providing the in-depth walkthrough of what you've been trying to do! It will help me to think through how to clarify how the cli and plugin work, how to use them, and how to debug problems.

**Comment by mr-majkel** [comment]
Hi @chipsenkbeil, thanks for your continuous work on distant! I have been playing with the first few releases in the past, and I'm waiting eagerly to test the new version when you feel it is more in beta shape - lack of docs for the alpha versions is a bit too big of an obstacle for me now:). Just letting you know, there are some of us lurking here and silently cheering on your work on this software!

**Comment by chipsenkbeil** [comment]
Progress on the config file with the closure of #158. With the latest commit, you can now generate a default configuration file via `distant generate config /path/to/config.toml`, which will output a documented config file with all options commented in a toml format. Today, this outputs the following:

```toml
###############################################################################
# All configuration specific to the distant client will be found under
# this heading
###############################################################################
[client]

# Specifies an alternative path to use when logging information while the
# client is running
# log_file = "path/to/file"

# Specifies the log level used when logging information while the client
# is running
#
# Choices are off, error, warn, info, debug, trace
# The default setting is info
log_level = "info"

# Alternative unix domain socket to connect to when using a manger (Unix only)
# unix_socket = "path/to/socket"

# Alternative name for a local named Windows pipe to connect to when using a
# manager (Windows only)
# windows_pipe = "some_name"

# Configuration related to the client's action command
[client.action]

# Maximum time (in seconds) to wait for a network request before timing out
# where 0 indicates no timeout will occur
timeout = 0

# Configuration related to the client's connect command
[client.connect]

# Additional options to provide, typically forwarded to the handler within
# the manager facilitating the connection. Options are key-value pairs separated
# by comma.
#
# E.g. `key="value",key2="value2"`
options = ""

# Configuration related to the client's launch command
[client.launch]

# Path to distant program on remote machine to execute via ssh; by default,
# this program needs to be available within PATH as specified when compiling
# ssh (not your login shell).
bin = "distant"

# Control the IP address that the server binds to.
#
# The default is `ssh', in which case the server will reply from the IP address
# that the SSH connection came from (as found in the SSH_CONNECTION environment
# variable). This is useful for multihomed servers.
#
# With --bind-server=any, the server will reply on the default interface and
# will not bind to a particular IP address. This can be useful if the
# connection is made through sslh or another tool that makes the SSH connection
# appear to come from localhost.
#
# With --bind-server=IP, the server will attempt to bind to the specified IP
# address.
bind_server = "ssh"

# Additional arguments to provide to the server when launching it.
args = ""

# Additional options to provide, typically forwarded to the handler within the
# manager facilitating the launch of a distant server. Options are key-value
# pairs separated by comma.
#
# E.g. `key="value",key2="value2"`
options = ""

# Configuration related to the client's repl command
[client.repl]

# Maximum time (in seconds) to wait for a network request before timing out
# where 0 indicates no timeout will occur
timeout = 0

###############################################################################
# All configuration specific to the distant generate option will be found under
# this heading
###############################################################################
[generate]

# Specifies an alternative path to use when logging information related
# to generation
# log_file = "path/to/file"

# Specifies the log level used when logging information related to generation
# Choices are off, error, warn, info, debug, trace
# The default setting is info
log_level = "info"

###############################################################################
# All configuration specific to the distant manager will be found under
# this heading
###############################################################################
[manager]

# Specifies an alternative path to use when logging information while the
# manager is running
# log_file = "path/to/file"

# Specifies the log level used when logging information while the manager
# is running
#
# Choices are off, error, warn, info, debug, trace
# The default setting is info
log_level = "info"

# Level of access control to the unix socket or windows pipe.
#
# * "owner": equates to `0o600` on Unix (read & write for owner).
# * "group": equates to `0o660` on Unix (read & write for owner and group).
# # "anyone": equates to `0o666` on Unix (read & write for owner, group, and other).
access = "owner"

# Alternative unix domain socket to listen on (Unix only)
# unix_socket = "path/to/socket"

# Alternative name for a local named Windows pipe to listen on (Windows only)
# windows_pipe = "some_name"

###############################################################################
# All configuration specific to the distant server will be found under
# this heading
###############################################################################
[server]

# Specifies an alternative path to use when logging information while the
# server is running
# log_file = "path/to/file"

# Specifies the log level used when logging information while the server
# is running
#
# Choices are off, error, warn, info, debug, trace
# The default setting is info
log_level = "info"

# Configuration related to the server's listen command
[server.listen]

# IP address that the server will bind to. This can be one of three things:
#
# 1. "ssh": the server will reply from the IP address that the SSH connection
#           came from (as found in the SSH_CONNECTION environment variable).
#           This is useful for multihomed servers.
# 2. "any": the server will reply on the default interface and will not bind to
#           a particular IP address. This can be useful if the connection is
#           made through ssh or another tool that makes the SSH connection
#           appear to come from localhost.
# 3. "{IP}": the server will attempt to bind to the specified IP address.
host = "any"

# Set the port(s) that the server will attempt to bind to.
#
# This can be in the form of PORT1 or PORT1:PORTN to provide a range of ports.
# With "0", the server will let the operating system pick an available TCP port.
#
# Please note that this option does not affect the server-side port used by SSH.
port = "0"

# If true, will bind to the ipv6 interface if host is any instead of ipv4
use_ipv6 = false

# Logic to apply to server when determining when to shutdown automatically.
#
# 1. "never" means the server will never automatically shut down
# 2. "after=<N>" means the server will shut down after N seconds
# 3. "lonely=<N>" means the server will shut down after N seconds with no connections
shutdown = "never"

# Changes the current working directory (cwd) to the specified directory.
# current_dir = "path/to/dir"
```
